const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const registry = require('./registry.cjs')
const { createStore } = require('./store.cjs')
const { createWorkerRuntime } = require('./assistantWorker.cjs')
const { createAssistantWorkerClient } = require('./assistantWorkerClient.cjs')
function fixture(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'sch-assistant-test-'))
  t.after(() => {
    const target = path.resolve(root)
    assert.ok(target.startsWith(path.resolve(os.tmpdir()) + path.sep + 'sch-assistant-test-'))
    fs.rmSync(target, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 })
  })
  registry.createTeam(root, { teamId: 'ONE', name: 'Synthetic One', folderName: 'ONE' })
  registry.createTeam(root, { teamId: 'TWO', name: 'Synthetic Two', folderName: 'TWO' })
  const [one, two] = registry.listTeams(root)
  registry.assignUserToTeam(root, 'me@test', 'ONE')
  const store = createStore(path.join(root, one.folderName))
  const outside = createStore(path.join(root, two.folderName))
  const shared = createStore(path.join(root, '_shared'))
  store.set('users', { 'me@test': { email: 'me@test', fullName: 'Synthetic User', status: 'approved', role: 'user' } })
  store.set('guides', [{ id: 'cloud', title: 'Cloud guide', version: '1.00', content: 'Den nye cloud ip adresse er 192.0.2.10. SYNTHETIC_ONLY' }])
  outside.set('guides', [{ id: 'other', title: 'Cloud external', content: 'OUTSIDE_GUIDE_SECRET' }])
  shared.set('active-sessions', { valid: { email: 'me@test', expiresAt: Date.now() + 60000 } })
  const config = { platformRoot: root, currentFolder: one.folderName, activeDir: store.dataDir, localDir: path.join(root, '_local'), diagnostics: { version: 'test', connected: true } }
  const runtime = createWorkerRuntime()
  const request = { token: 'valid', question: 'hvad er den nye cloud ip adresse', language: 'da' }
  const query = () => runtime.call('query', [request], config)
  return { root, store, shared, outside, one, two, config, runtime, request, query }
}
test('real worker runtime reuses guide cache and retrieves the exact reported question', t => {
  const { query, runtime } = fixture(t)
  const first = query()
  const second = query()
  assert.equal(first.mode, 'retrieval')
  assert.match(second.text, /192\.0\.2\.10/)
  assert.ok(runtime.stats().hits >= 1)
  assert.ok(!second.text.includes('OUTSIDE_GUIDE_SECRET'))
  assert.ok(!JSON.stringify(second.sources).includes('words'))
})

test('historical follow-up rechecks current role and detects edits of the same snapshot', t => {
  const { runtime, store, config, request } = fixture(t)
  store.set('users', { 'me@test': { email: 'me@test', fullName: 'Synthetic User', status: 'approved', role: 'manager' } })
  store.set('guide-versions-cloud', [{ version: '0.99', snapshot: { content: 'NY CLOUD IP ADRESSE 192.0.2.30' } }])
  const followup = { ...request, question: 'hvad er den gamle så?', conversation: [request.question] }
  const evidence = runtime.call('query', [followup], config)
  assert.ok(evidence.sources.some(source => source.history))
  runtime.call('revalidateSources', [followup, evidence], config)
  store.set('guide-versions-cloud', [{ version: '0.99', snapshot: { content: 'NY CLOUD IP ADRESSE 192.0.2.40' } }])
  assert.throws(() => runtime.call('revalidateSources', [followup, evidence], config), /historikken blev ændret/)
  store.set('users', { 'me@test': { email: 'me@test', fullName: 'Synthetic User', status: 'approved', role: 'user' } })
  assert.throws(() => runtime.call('revalidateSources', [followup, evidence], config), /ikke adgang/)
  assert.ok(!runtime.call('query', [followup], config).sources.some(source => source.history))
})
test('login preparation warms only authorized published guides before the first question', t => {
  const { runtime, config, request, store, query } = fixture(t)
  store.set('guide-review-requests', [{ id: 'draft', status: 'pending', submittedBy: 'me@test', proposedGuide: { title: 'Cloud draft', content: 'DRAFT_NOT_PUBLISHED' } }])
  const prepared = runtime.call('prepare', [request], config)
  assert.deepEqual(prepared, { guideCount: 1, stepCount: 1 })
  assert.ok(!JSON.stringify(prepared).includes('192.0.2.10'))
  assert.equal(runtime.stats().entries, 1)
  const hits = runtime.stats().hits
  const answer = query()
  assert.ok(runtime.stats().hits > hits)
  assert.ok(!answer.text.includes('DRAFT_NOT_PUBLISHED'))
  assert.ok(!answer.text.includes('OUTSIDE_GUIDE_SECRET'))
})
test('editing/deleting a cached guide is reflected without restarting or retaining stale IP', t => {
  const { query, store } = fixture(t)
  query()
  store.set('guides', [{ id: 'cloud', title: 'Cloud guide', version: '1.01', content: 'Den nye cloud ip adresse er 192.0.2.20. SYNTHETIC_ONLY' }])
  const edited = query()
  assert.match(edited.text, /192\.0\.2\.20/)
  assert.ok(!edited.text.includes('192.0.2.10'))
  store.delete('guides')
  // Efter fase 4 svarer Hubert med app-viden i stedet for en blank afvisning,
  // saa der kan ligge en app-guide-kilde. Pointen er at INTET guide-indhold
  // overlever sletningen.
  const afterDelete = query()
  assert.ok(!afterDelete.sources.some(source => source.kind === 'guide'))
  assert.ok(!afterDelete.text.includes('192.0.2.'))
})
test('a revoked/expired login cannot reuse a warm guide cache', t => {
  const { query, shared } = fixture(t)
  query()
  shared.set('active-sessions', {})
  assert.throws(query, /Log ind/)
  shared.set('active-sessions', { valid: { email: 'me@test', expiresAt: 1 } })
  assert.throws(query, /Log ind/)
})
test('account approval and manager privileges are read fresh, not remembered with guide cache', t => {
  const { query, store, runtime, config, request } = fixture(t)
  query()
  store.set('users', { 'me@test': { email: 'me@test', fullName: 'Synthetic User', status: 'pending', role: 'manager' } })
  assert.throws(query, /ikke godkendt/)
  store.set('users', { 'me@test': { email: 'me@test', fullName: 'Synthetic User', status: 'approved', role: 'user' } })
  assert.throws(() => runtime.call('getRecord', [{ ...request, moduleId: 'administration', recordId: 'anything', teamId: 'ONE' }], config), /ikke adgang/)
})
test('external guide access revocation and expiry remove cached evidence immediately', t => {
  const { outside, runtime, request, config, two } = fixture(t)
  outside.set('guide-access-requests', [{ guideId: 'other', requestingUserEmail: 'me@test', requestingTeamCode: 'ONE', status: 'approved', expiresAt: new Date(Date.now() + 60000).toISOString() }])
  assert.equal(runtime.call('getGuide', ['valid', undefined, two.teamId, 'other'], config).guide.id, 'other')
  outside.set('guide-access-requests', [])
  assert.throws(() => runtime.call('getGuide', ['valid', undefined, two.teamId, 'other'], config), /ikke adgang/)
  assert.ok(!JSON.stringify(runtime.call('query', [{ ...request, question: 'guide cloud external' }], config)).includes('OUTSIDE_GUIDE_SECRET'))
})
test('removing shared-guide team membership invalidates cache without disclosing old guide', t => {
  const { shared, runtime, config, one } = fixture(t)
  shared.set('shared-guides', [{ id: 'shared', title: 'Shared', content: 'SHARED_GUIDE_TEST', sharedWithTeamCodes: [one.folderName] }])
  assert.equal(runtime.call('getGuide', ['valid', undefined, one.teamId, 'shared'], config).guide.id, 'shared')
  shared.set('shared-guides', [{ id: 'shared', title: 'Shared', content: 'SHARED_GUIDE_TEST', sharedWithTeamCodes: [] }])
  assert.throws(() => runtime.call('getGuide', ['valid', undefined, one.teamId, 'shared'], config), /ikke adgang/)
})
test('Hubert never revives an older approval after a newer rejection in the guide library', t => {
  const { outside, runtime, request, config, two } = fixture(t)
  const approval = { guideId: 'other', requestingUserEmail: 'me@test', requestingTeamCode: 'ONE', status: 'approved', requestedAt: '2026-09-01T00:00:00Z', expiresAt: new Date(Date.now() + 60000).toISOString() }
  outside.set('guide-access-requests', [approval])
  assert.equal(runtime.call('getGuide', ['valid', undefined, two.teamId, 'other'], config).guide.id, 'other')
  outside.set('guide-access-requests', [approval, { ...approval, status: 'rejected', requestedAt: '2026-09-02T00:00:00Z' }])
  assert.throws(() => runtime.call('getGuide', ['valid', undefined, two.teamId, 'other'], config), /ikke adgang/)
  assert.ok(!JSON.stringify(runtime.call('query', [{ ...request, question: 'cloud external guide' }], config)).includes('OUTSIDE_GUIDE_SECRET'))
})
test('source revalidation rejects an edit made during model generation, even at same version', t => {
  const { query, store, runtime, request, config } = fixture(t)
  const answer = query()
  store.set('guides', [{ id: 'cloud', title: 'Cloud guide', version: '1.00', content: 'Den nye cloud ip adresse er 192.0.2.30.' }])
  assert.throws(() => runtime.call('revalidateSources', [request, answer], config), /guide blev ændret/)
})
test('shared meal-plan routing matches the actual hub rather than obsolete team storage', t => {
  const { shared, store, runtime, request, config } = fixture(t)
  shared.set('meal-plan-weeks', [{ year: 2026, weekNumber: 36, meals: { monday: 'CURRENT_SHARED_MENU' } }])
  store.set('meal-plan-weeks', [{ year: 2026, weekNumber: 36, meals: { monday: 'OBSOLETE_TEAM_MENU' } }])
  const answer = runtime.call('query', [{ ...request, question: 'hvad fik vi at spise i uge 36 2026?' }], config)
  assert.match(answer.text, /CURRENT_SHARED_MENU/)
  assert.ok(!answer.text.includes('OBSOLETE_TEAM_MENU'))
})
test('worker dispatcher refuses arbitrary key, path and write operations', t => {
  const { runtime, config } = fixture(t)
  for (const method of ['readFile', 'get', 'set', 'delete', 'constructor']) assert.throws(() => runtime.call(method, [], config), /Ukendt/)
})
test('actual subprocess RPC preserves guide authorization and can reuse its cache', async t => {
  const { config, request } = fixture(t)
  const client = createAssistantWorkerClient({ getState: () => config, timeoutMs: 10000 })
  t.after(() => client.stop())
  const first = await client.session().query(request)
  const second = await client.session().query(request)
  assert.match(first.text, /192\.0\.2\.10/)
  assert.equal(first.text, second.text)
  await assert.rejects(() => client.session().getGuide('valid', undefined, 'TWO', 'other'), /ikke adgang/)
})
function slowClient(t, options = {}) {
  const state = { platformRoot: 'synthetic', activeDir: 'synthetic', currentFolder: 'ONE' }
  const client = createAssistantWorkerClient({ getState: () => state, workerPath: path.join(__dirname, 'fixtures', 'assistantSlowWorker.cjs'), timeoutMs: 2000, ...options })
  t.after(() => client.stop())
  return { client, state }
}
test('a synchronously blocked child leaves the parent responsive and gets timed out', async t => {
  const { client } = slowClient(t)
  await client.session().moduleCatalog()
  let ticks = 0
  const timer = setInterval(() => ticks++, 20)
  t.after(() => clearInterval(timer))
  await assert.rejects(() => client.session().query({ question: 'slow' }), /tog for lang tid/)
  assert.ok(ticks >= 5, 'Parent event loop must continue while child storage is blocked')
  assert.deepEqual(await client.session().moduleCatalog(), { synthetic: true })
})
test('stop cancels pending work and prevents an old request session from restarting the worker', async t => {
  const { client } = slowClient(t)
  const session = client.session()
  const pending = session.query({ question: 'slow' })
  client.stop()
  await assert.rejects(() => pending, /afbrudt/)
  await assert.rejects(() => session.authorize('valid'), /afbrudt/)
  assert.deepEqual(await client.session().moduleCatalog(), { synthetic: true })
})
test('ordinary panel close/cancel preserves an idle worker and does not cancel guide preparation', async t => {
  const { client } = slowClient(t)
  const session = client.session()
  await session.moduleCatalog()
  client.cancel()
  assert.deepEqual(await session.moduleCatalog(), { synthetic: true })
  const preparation = session.prepare({ token: 'synthetic' })
  client.cancel()
  assert.deepEqual(await preparation, { synthetic: true })
})
test('scope changes reject in-flight results; worker crashes return an error instead of hanging', async t => {
  const { client, state } = slowClient(t)
  const session = client.session()
  state.currentFolder = 'TWO'
  await assert.rejects(() => session.query({ question: 'anything' }), /Hubben blev ændret/)
  await assert.rejects(() => client.session().query({ question: 'crash' }), /baggrundsproces stoppede/)
  assert.deepEqual(await client.session().moduleCatalog(), { synthetic: true })
})
